### ISSUE TITLE
Make project name an editable field in the editor

### ISSUE THREAD

**Issue by AndyLindsay** [parallaxinc/solo#106]
The Save and Open buttons in the editor have made saving and opening projects a more natural process with fewer steps.  It now has that quick and snappy feel of unimpeded progress. 
 To complete the open, save, save as picture, another enhancement could make changing the project name quicker and more intuitive too.  

Currently, the user has to click the Hamburger menu and select Edit project details to change the project name.  It would further simplify the user experience if he/she could just click the project name displayed in the upper-right to change it.  On click, the field could become editable, and on exit, it should update the .svg's project name meta data.

The micro:bit online MicroPython editor has a nice example of something similar.  See the Script Name field in the upper-right of this editor: https://python.microbit.org/v/beta  

True, the user will still have to go into Edit project details to change the board type or project details, but that's not as common of an occurrence as changing the project name.  In class, the user is asked to change the project name twice in a given activity.  Later activities may direct the user to reopen one of these projects.  

In a given activity, they start with the test code, and then change it's name before modifying it in the Try This section.  When they get to the your turn section, they change the name of the code again.  The project description can be chosen to be generic enough that it will not need to be changed with each update to the project name.  Since the project name is used as the basis for the Save name, it also makes it clear hot to direct them to open a given file they worked on earlier.

**Comment by zfi** [comment]
After applying PR #120 and #143, there are issues with the toolbar and the the editable field itself.

* The editable field appears to have a fixed width of about 20 characters. Any additional characters in the project name are truncated in the display. 
* The project name field appears to permit characters that are OS file system unfriendly. These characters are replaced with underscores when the project is saved.
* The project name field appears to act links a textfield instead of at textbox in that pressing the enter key creates a newline in the field. The only way I could find to leave the field was to click outside of the text area.
* The toolbar buttons 'New', 'Open', and 'Save' have lost their styles. They continue to operate as expected.

<img width="265" alt="Screen Shot 2019-11-01 at 12 00 30 PM" src="https://user-images.githubusercontent.com/8442260/68049208-88679480-fc9f-11e9-8af1-e9580c110d27.png">

<img width="265" alt="Screen Shot 2019-11-01 at 12 04 20 PM" src="https://user-images.githubusercontent.com/8442260/68049542-6ae6fa80-fca0-11e9-8eef-e82e3c60b060.png">

**Comment by zfi** [comment]
@AndyLindsay reported in #147 :
> Given a project name of: Abc Defg * 1234
> 
> The saved filename becomes: abc_defg___1234
> 
> The file download behavior I am familiar with in other systems preserves capitalization and spaces and only removes OS reserved characters, like the *. Could we do that here too?

**Comment by MatzElectronics** [comment]
Still need to try to left-justify the text in the field when the user leaved the field (the beginning of the project name can get cut off if it's really long and the user left their cursor toward the end of the field).

**Comment by MatzElectronics** [comment]
Can this be closed now?

**Comment by pjewald** [comment]
This appears to be operational. Closing the issue.
