### ISSUE TITLE
Safari Download SimpleIDE files does not save the C code file

### ISSUE THREAD

**Issue by AndyLindsay** [parallaxinc/solo#134]
Submitted by dgately through learn@parallax.

On my macOS 10.14.6 system, running Safari, the "Download SimpleIDE files" option only saves the .side file and NOT the actual C code file. This does not happen with Google Chrome, Brave and FireFox browsers!

Steps to reproduce:

1. Go to solo.parallax.com in Safari on a macOS system
2. Launch BlocklyPropClient app (??? still need this for Solo?)
BTW: The app's Browser button points to: "http://blockly.parallax.com/blockly". Should there be a solo button as well?
3. Click Connect button, and go back to the web browser (to: solo.parallax.com)
4. Create a simple BlocklyProp program (mine is attached to this email)
5. Test the program (verify that it compiles/creates C code)
6. Select the "Download Simple files" menu item... You'll be asked to name/rename the project.

Result:
The .side project file is downloaded to my Downloads folder but the .c file, that was created from the BlocklyProp code is not downloaded.

This issue does NOT appear for FireFox, Brave or Google Chrome browsers! Is this an Apple Safari bug???

**Comment by AndyLindsay** [comment]
.svg files not supported, so here is a picture of the program.

![image](https://user-images.githubusercontent.com/11575415/67598844-7035c980-f723-11e9-8b57-fd2e3870f8dc.png)

**Comment by MatzElectronics** [comment]
There is an issue I think with all browsers, and we've never gotten around
to fixing it,  so thank you for raising the issue.  It stems from the fact
that browsers limit downloads to one file per user interaction, to prevent
a site from bombarding a users computer.   Since simple IDE requires two
files, we either need two clicks, or zipping them together (like we just
did with the bulk project download).  I'm guessing that what you're
experiencing is a browser getting one file and not the other, and it seems
that which file you get is browser dependent.

**Comment by PropGit** [comment]
Regarding item# 2, yes, it's still needed.  We'll be updating the software and the link(s) it goes to soon.

**Comment by pjewald** [comment]
Is the correction for this going to be archiving the two files into a .zip file? That seems to be a simpler result that trying to get the user to download to separate files.

**Comment by MatzElectronics** [comment]
Yes, that's the plan.  There might be a UI tweak, and there is an
opportunity to use filesaver.js instead of the mess of code that currently
is responsible for packaging the blob to be downloaded.

**Comment by zfi** [comment]
Verified that the menu selection generates a .zip file the contains the .c and .side files.
Closing this issue.
