### ISSUE TITLE
Request: Linkable example projects

### ISSUE THREAD

**Issue by dlcarrier** [parallaxinc/solo#155]
We often link to BlocklyProp projects, to document how to perform an action or use a product.  It would be beneficial if we could retain this ability with BlocklyProp Solo.  Possible solutions include:

* Allowing Parallax employees to save projects to Solo
* Encoding a BlocklyProp program, into the URL
* Embedding a link to an SVG file, or equivalent, into the URL

**Comment by zfi** [comment]
The first option is not possible because Solo was designed to store projects on the user's local disk system. Storing project to Solo is not supported. The remaining options are really not specific to Solo and should be addressed elsewhere.

**Comment by MatzElectronics** [comment]
This should be pretty easy to implement.  Just like we have `?openFile=true`, we could have `?openUrl=https://solo.parallax.com/examples/exampleproject1.svg`, and when the openUrl request is detected, do a get request for it, and use the fetched svg just like when it's fetched from a file.  Shouldn't take more than a couple of lines of code, and then the examples filder could just be maintained in the CDN via github.

**Comment by zfi** [comment]
This project (Solo) does not rely on a CDN in the same way as the BlocklyProp project does. The code that was formerly drawn from the CDN was integrated directly into the project some time ago. There are no references to the BlocklyProp-cdn project in this project. 

Now, embedding the example projects into the project is technically possible but not without some administrative overhead. Each change to the examples folder would require a redeployment of the web server containers since the containers themselves are immutable by design.

I think we need to examine alternatives that do not impact the simplicity that Solo represents. For example, why not host the example projects on another web site, such as Learn?

**Comment by MatzElectronics** [comment]
We can link directly from any URL pointing to any site the file is hosted on.  An attachment on learn with a public URL would probably suffice, we'd just to mind any potential CORS issues with projects not on the same site.

**Comment by zfi** [comment]
This feature request complicates the simplicity of project management in Solo. It may be possible to update the Open Project dialog to accept a URL to a project file but it also comes with some inherent risks, such as the possibility of downloading a Trojan Horse project file. I don't think we're ready for that kind of excitement at this point.
