### ISSUE TITLE
Give Project Name field an editable text field appearance as a queue for users

### ISSUE THREAD

**Issue by AndyLindsay** [parallaxinc/solo#166]
This is a finishing touch on #106.

I do not expect many users to figure out that they can change the project name in the upper-right project name field if it just looks like text.  If it instead looks like an editable text field, it will queue the users that they can edit the filename.  

It should look something like this:

![image](https://user-images.githubusercontent.com/11575415/68997745-82a4ae00-085e-11ea-9650-ce56bc40b48e.png)

**Comment by pjewald** [comment]
The current implementation displays a border when the user clicks on the project name. Perhaps we simply leave the border visible at all times. If the user edits the project name, we could change the background of the control to a very light grey to indicate that editing it happening as in the second example below.

**Current Edit State**
<img width="304" alt="Screen Shot 2019-11-16 at 11 08 51 AM" src="https://user-images.githubusercontent.com/11216070/68998004-7ff78800-0861-11ea-85a9-cd03a7a7867b.png">

**Proposed Edit State**
<img width="304" alt="Screen Shot 2019-11-16 at 11 16 23 AM" src="https://user-images.githubusercontent.com/11216070/68998091-9ce08b00-0862-11ea-801a-171826821c96.png">

**Comment by AndyLindsay** [comment]
I would suggest looking at the behavior of the micro:bit Python online editor for an example of the desired behavior.

https://python.microbit.org/v/beta

**Comment by MatzElectronics** [comment]
Before we bodge this one in - we need to look at the top bar more holistically.  It's getting cluttered, and this will impact that.  I don't really have an answer here, but we have already clobbered the appearance when the screen is narrow (see #135).

One alternative is to add a "new feature" modal with a GIF showing off the new functionality.  We can add a cookie so that once a user has dismissed it, it won't show again until we trigger another new feature.

**Comment by AndyLindsay** [comment]
The picture in #135 is not at all what I'm seeing.  Below is what I see when the browser is made narrow.  Also, I really think it's a non-issue because nobody would be able to do block coding with a window that narrow.    

![image](https://user-images.githubusercontent.com/11575415/69026838-6fd6ca00-0981-11ea-9b91-aaf4b8da614f.png)

**Comment by MatzElectronics** [comment]
Correct - what's in #135 is a mockup of what it could look like if there
was a deliberate effort to make it compatible.  I agree - going completely
vertical isn't practical, but even dropping below 765px wide clobbers the
UI (not unusable, but ugly).

Additionally, dropping below 765px on the main page makes the links
completely disappear, rendering the site unusable.

I feel that we should be supporting resolutions down to 640x480.

**Comment by PropGit** [comment]
Idea:  The user is moving the mouse over that region of the screen quite often because of the other controls there.  If for some reason we don't want the project name to always have a border, we can make it appear on mouseover and stay upon focus (ie: click event that places the blinking cursor in the field).

**Comment by zfi** [comment]
Let's stay focused on the issue presented here. Please open a new issue for the UI redesign.

**Comment by zfi** [comment]
It appears the #135 is getting at a UI redesign by focusing on narrow page formatting.
