### ISSUE TITLE
Deprecate configure_client function

### ISSUE THREAD

**Issue by zfi** [parallaxinc/solo#203]
The configure_client function in blocklypropclient.js is directly tied to the legacy BlockyProp Client. The functionality provided is not required with the new BlocklyProp Launcher which uses web sockets to communicate to the connected device.

Mark the function as deprecated and note this wherever the function is referenced.

**Comment by PropGit** [comment]
Actually, the BP Launcher does use this configuration.  It's how the site (browser) finds and connects to the BP Launcher... BP Launcher sets up an HTTP Listener on that port and a websocket server to upgrade the connection to ws.

![image](https://user-images.githubusercontent.com/1266318/71017456-6ee1a700-20ab-11ea-9cec-3991f6d0714b.png)

When the site and the BP Launcher port configuration* doesn't match, no connection occurs.  This is; however, something we've never had to mess with for any customer (yet), and as it stands, the site (Solo and probably Production) doesn't save this configuration as session information, so refreshing the browser or starting a new session resets it back to its defaults, making the feature more limited in its effective use should in need be used.

Perhaps we can simply *hide* it on both sides so that it's easy to reimplement it should there be a customer use case that warrants it?

*In the process of answering this, I noticed that BP Launcher never uses the URL, only the port... which makes sense because it can only set up the listener on whatever device it's running on, which will always be localhost from it's perspective.  I can remove that URL setting on the BP Launcher side permanently, but I still think we should simply hide the other functionality rather than remove it completely (for future ease in flexibility).

**Comment by zfi** [comment]
Where can I find information about the handshake between the Launcher and the browser code? I still feel like I'm not understanding how the browser and the Launcher are using HTTP to get to web socket.

**Comment by zfi** [comment]
@PropGit - Where can I find information about the handshake between the Launcher and the browser code?

**Comment by PropGit** [comment]
The handshake to start the WebSocket is started with an HTTP request.  That request is to upgrade the connection (same TCP/IP connection) to a WebSocket protocol and the rest of the communication is handled over WS:// using the same TCP/IP connection.  Here's a tutorial I found:  https://sookocheff.com/post/networking/how-do-websockets-work/

The launcher is using a lightweight server that handles websockets; it's inside of the launcher's http.js file.  http.Server and http.WebSocketServer.

I'm not too familiar with it because that code came from Google and was included and made functional by @MatzElectronics.

Is there a problem with it?

**Comment by MatzElectronics** [comment]
I'd prefer we leave this here for now.  It is the only way to change the path and port to the client, and while it hasn't been used much - I have used it before (port blocked by a school), etc.  There are some other scenarios I can think of needing this as well.

I'd actually like to see the path/port setting to the compiler service exposed as well.  I can envision a case where students might have solo on their chromebooks, and talk to a client/compile service that might be a single PC in the room.

**Comment by PropGit** [comment]
Re: compiler service - Solo no longer uses a path/port setting, but rather has been enhanced to use a URI that is parsed server-side to redirect to the compiler when requested.  This is to prevent a problem one school experienced where the port was blocked by the school IT policy; they could build projects but could never compile.

**Comment by zfi** [comment]
Solo handles compilation requests based on how the application was accessed. If the browser is connecting to http://solo.parallax.com, the system expects compilation requests to arrive on port 5001. 

However, if the browser is connecting to https://solo.parallax.com, the system expects the compilation request to arrive on port 443. The load balance will examine the request and forward it to the cloud compiler internally on port 5001. The results are then returned to the browser on port 443.

As @PropGit notes, accessing Solo using HTTPS ensures that all traffic flows via port 443. That makes life a little easier for the local school district IT folks.

**Comment by pjewald** [comment]
Let's leave the feature in place for now. I'll withdraw the request and close this issue.
