### ISSUE TITLE
Solo tries to open project, then vaporizes

### ISSUE THREAD

**Issue by kgracey** [parallaxinc/solo#249]
I have found myself unable to open projects with Solo. Here's what I'm seeing. 

[https://youtu.be/Ua61Evw-K3A ](url)

**Comment by kgracey** [comment]
I should add that the project I'm trying to open was originally created for another board type (Other). @MatzElectronics converted it so I could open in Solo, with PAB as the board type. This worked fine for two days, but is now broken. I am able to open other projects stored locally, but not this one. So, this problem is likely unique to me and a result of converting the board type behind the scenes. Nonetheless, it's not clear why it worked fine, then broke.

**Comment by zfi** [comment]
@kgracey, can I get a copy of the project file you are using? The redirect to the home page is happening because there is something in the project that is generating an error when the project is loading. The application detects that and - for now - drops back to the home page because there is no valid project loaded.

**Comment by zfi** [comment]
The project file contained a number of serial transmit blocks, all set to pin pair 0,0. This is likely caused by an error in the serial transmit block persistence code that was not properly emitting the pin pair when saving the file.

The updates in v1.4.1-b1 correct this issue. The original project loads but all of the serial transmit pin pairs are set to 0,0. I reset them to 5,4 as defined in the serial init block; saved the project and verified that the project now loads correctly and compiles.
