### ISSUE TITLE
Project naming - how should it work?

### ISSUE THREAD

**Issue by kgracey** [parallaxinc/solo#250]
Hey there, 

This issue may not be relevant or fixable with our current design, and other tools (like Microbit's Python editor) may face similar constraints. Anyway, it didn't work the way I thought it might. Maybe it's something for the "Getting Started with Solo" tutorial. Please take a look:

[https://youtu.be/OukHym24vhE](url)

If unfixable, close the issue.

**Comment by kgracey** [comment]
This may tie to issue 245, in which case both of these may be closed after further inspection by @PropGit and others if adjustments to the interface are not possible.

**Comment by zfi** [comment]
The reason this is happening is due to how the project name is stored with the project. The project name is stored in the .svg file as metadata. Renaming the .svg file does not alter the metadata so the project name as displayed in the project is unaltered.

Maybe we need to rethink whether the project name should be stored in the file metadata?

**Comment by zfi** [comment]
The internal consensus is to strip the project name metadata and use the project filename as the project name.

**Comment by PropGit** [comment]
@zfi Love it so far... huge improvement (and I have customer input that amplifies the need for this).

Can we add a little more smarts to this feature though?  

Current Behavior in SoloCup:
- As the project is saved multiple times, the Chrome Browser automatically appends and adjusts a unique part " (#)" to the end of the file, rather than overwriting the original.  Note also that there's a space before the first parenthesis.
- When one of the later files is opened, the full filename (minus the extension) is used as the new Project Name metadata, including the auto-updated number.  ie: "Test" becomes "Test (3)"
-  Then, the next save produces "Test (3) (1)" then "Test (3) (2)" and so on.  Further opening and saving produces "Test (3) (2) (1)" etc.

Can we have it instead take the filename, truncate off any trailing " (#)" (just before the extension) if that appears, and compare _that_ to the Project Name metadata... then if there's a difference, use _that_ as the new Project Name metadata?

Doing the above will naturally result in students projects that they open the next day, say "Test (15)", opening up and having the expected project name, and the next save becoming "Test (16)".
