### ISSUE TITLE
Symbols in comments stop compiler (server error 500)

### ISSUE THREAD

**Issue by VonSzarvas** [parallaxinc/solo#283]
Add comment block with this text: ActivityBot 360°
Compiler error : "Compile... A compiler server error '500' has been detected"

![2020-02-19 11_15_22-BlocklyProp Solo](https://user-images.githubusercontent.com/11635798/74824979-6571f680-5309-11ea-8951-fab706535d66.png)

**Comment by MatzElectronics** [comment]
We should be able to apply a regex and restrict the comments to lower-ASCII.  We should investigate this for other blocks like `text_string` that can take a similar input.

**Comment by zfi** [comment]
The compiler is supposed to ignore any comment strings, even one's with extended characters, so I don't believe that is the problem. Instead, I suspect that this is an issue related to handling UTF-8 strings, which became a default in Python3. The compiler service code has had issues with this in the past. Let's verify what the exact issue in on the compiler service before we add even more RegEx to the browser code.

**Comment by zfi** [comment]
The compiler is reporting the following:

```
  File "./PropCCompiler.py", line 96, in compile
    source_file.write(file_content)
UnicodeEncodeError: 'ascii' codec can't encode character '\xb0' in position 150: ordinal not in range(128)
[pid: 11|app: 0|req: 1/3] 172.18.0.1 () {46 vars in 788 bytes} [Wed Feb 19 18:16:41 2020] POST /single/prop-c/compile => generated 290 bytes in 19 msecs (HTTP/1.1 500) 4 headers in 150 bytes (1 switches on core 0)
```

This is happening because the compiler server is trying to return the compiled results as an byte stream. The degree symbol is valid in UTF-8 bit is not in the ASCII implementation.

Let's take a look at why the return from the compiler has to be ASCII before we proceed.

@PropGit, do you think there would be an issue with embedding this or any other symbol in the binary that we send to the Propeller? I'm trying to determine if there is a hard reason that we are transferring the data as ASCII.

**Comment by zfi** [comment]
Created tracking issue in the Cloud Compiler repository for this issue.

**Comment by PropGit** [comment]
Is it really compiling successfully but failing to be transmitted back to the client because of the encoding?

We don't support non-ASCII characters for executable code in Spin/PASM compilers, but I'm betting PropGCC does accept Unicode characters in comments by default, though I've never seen the issue come up or know of anyone who has tried.  

It should be okay for it to be embedded in the ELF that's returned; the only issue being if it's included as textual data for processing during execution, the code processing it would have to know to treat it as UTF-8 and that's outside the scope of this problem from what I understand of the issue.

**Comment by pjewald** [comment]
The error was actually happening when the compiler server was converting the byte stream from the browser into temporary files that will be fed to the compiler. The compiler has been updated to permit UTF-8 characters in these temporary files.

The compiler discards comments, so that isn't an issue but it would seem that it would be possible to place UTF-8 characters into string variables. See the trivial example below. In this case, the test string might get truncated or the symbol replaced with (don't know) when the code is executed. I'm trying to be sure that we don't break anything with UTF-8 characters.

<img width="319" alt="Screen Shot 2020-02-19 at 1 12 48 PM" src="https://user-images.githubusercontent.com/11216070/74877022-9823eb00-5319-11ea-8eaf-7d27e448ef9b.png">

```
// ------ Libraries and Definitions ------
#include "simpletools.h"

// ------ Global Variables and Objects ------
char item[64];



// ------ Main Program ------
int main() {

  while (1) {
    // Looping... 360°
    strcpy(item, "Looping... 360°"); // Save string into variable item.
  }
}
```

**Comment by PropGit** [comment]
I suspect that will work (for the compiler and systems involved) though I couldn't say for sure.

Here's an issue I can think of:

For a data string containing ASCII characters in the Latin Extension (128-255), when ANSI-encoded, would compile to the expected range (128-255, single-byte each; however, that same code when UTF-8-encoded, would compile to a longer string containing two bytes per character that was in the 128-255 range... the string is longer, taking more space for the data, which should compile in most if not all cases, but execution may fail in a bad way and at unpredictable times due to the extra space consumed, or the encoding, which may have been unexpected by one or both of the developer and library code to process such data in the executable.

I can't think of a way to ensure UTF-8 encoding in that case would work properly without ensuring the use of a wide-string capable library for processing such data.

**Comment by pjewald** [comment]
The compiler service has been updated on SoloCup. I was able to verify that code containing the degrees symbol compiles successfully. 

@VonSzarvas - give it a shot and let me know if you see the same result.

**Comment by VonSzarvas** [comment]
solo still fails, and solocup compiles fine.

result!

**Comment by pjewald** [comment]
That is exactly the expected result. 
Closing this issue.

**Comment by PropGit** [comment]
Ironically, the degree symbol (°) that we've been using in this issue is indeed part of the Latin Extension in the ASCII set and the proper Glyph appears at that location (176) in fonts like Courier.  It should have been stored and displayed properly if the encoding happening in the BlocklyProp syster were a true ANSI encoding (8-bit ASCII) but it appears the encoding was originally storing only 7-bit ASCII.

Regardless, I've verified that with the changes made, execution doesn't _fail_ (meaning, doesn't bomb, but rather performs as expected under the conditions) when UTF-8 encoded characters above 127 are included and processed in strings.

The Unicode characters are entered into the strings as UTF-8 and are processed as ASCII characters in all cases I tested.  No execution violations found, though the results are, of course, not what a user would expect logically.

**Test 1 - Storage of Unicode Character and Terminal Output of String**
![image](https://user-images.githubusercontent.com/1266318/74941171-72452780-53a7-11ea-8668-f3cb8d10a436.png)
String expands by two bytes, as expected, but Terminal doesn't display Unicode character (rather displays two characters).  This is expected unless we fully support UTF-8 in strings and in all text-processing library functions plus the terminal.

**Test 2 - Appending Unicode Character to String and Terminal Output of String**
![image](https://user-images.githubusercontent.com/1266318/74944826-7d01bb80-53ab-11ea-9fdb-1ce2b4266e58.png)
![image](https://user-images.githubusercontent.com/1266318/74944837-812dd900-53ab-11ea-83fc-25567b3e0d24.png)

To be clear: This is now working as I expect, under the conditions we have.
