### ISSUE TITLE
Serial blocks not exposing TX/RX pins until blocks are moved

### ISSUE THREAD

**Issue by zfi** [parallaxinc/solo#365]
The RXTX pull down does not appear on the Serial blocks when initially dragged onto the canvas. The pull down does not appear unless the Serial initialize block is dragged from it's current location on the canvas. The pull down disappears on all Serial blocks when any non-init Serial block is deleted. 

Initial

<img width="486" alt="Screen Shot 2020-03-09 at 4 00 39 PM" src="https://user-images.githubusercontent.com/8442260/76264599-84d0b500-621f-11ea-936b-2740cc443313.png">

After drag

<img width="486" alt="Screen Shot 2020-03-09 at 4 00 58 PM" src="https://user-images.githubusercontent.com/8442260/76264623-931ed100-621f-11ea-9133-145d087544c3.png">

After block delete

<img width="486" alt="Screen Shot 2020-03-09 at 4 01 18 PM" src="https://user-images.githubusercontent.com/8442260/76264651-a467dd80-621f-11ea-913b-2b24638f5f78.png">

**Comment by zfi** [comment]
Additional details:
* When the Serial blocks hit the canvas, they all believe that they have a single set of pins (5-4). 
* When the init block is dragged, the serial pin array (serpin) becomes an array with two elements, (0-0, 5-4).
* When the non-init blocks refresh from the drag event, they each see that the serpin array contains multiple elements and then displays the dropdown to select between the two pairs of pins (0-0, 5-4).

At this point, I am unable to determine what was designed vs what is actually happening.

**Comment by MatzElectronics** [comment]
Got it - I've been working on this tonight - and it's a similar issue to some we've worked on before.  We have a number of blocks that allow multiple initializers.

The idea here is that if you only use one initializer, then the pin menu should stay hidden.
The pin menu should reveal itself if there are two initializer blocks that have different values.  Dragging should not affect the state of the menu, only addition of, deletion of, or changes to the pin values in the serial init blocks.

On a related note, now that I've re-done some variant of this code several times, I keep finding more efficient ways to refactor it.  The good (?) news it that this will affect almost all serial protocol blocks, since the functions for this are copied to each of the blocks.

Once we shake this out, I'd recommend applying this newer method for the color pal blocks, the RGB-LED blocks (both of these allow multiple initializers), array, and named constants blocks as we are able.

**Comment by zfi** [comment]
So the RXTX element should remain invisible until - and only when - there is more that one serial session?  I wasn't sure where the 0,0 pin assignment was coming from and the code was squirrely enough that I decided not to go there without understand the design goals.

When you say that the functions are copied to each block, is this literally the same code copied to each block or is there a possibility to refactor that into something a lot more efficient but understandable?

**Comment by MatzElectronics** [comment]
Yes, only when there are multiples.

And yes, there is a function in the first block, and then lines that look like this in each subsequent block that should have the same behavior:

```
    mutationToDom: Blockly.Blocks['serial_send_text'].mutationToDom,
    domToMutation: Blockly.Blocks['serial_send_text'].domToMutation,
    updateSerPin: Blockly.Blocks['serial_send_text'].updateSerPin,
    onchange: Blockly.Blocks['serial_send_text'].onchange
```

The [0,0] came from a default value that was supposed to erased on load, but wasn't.

**Comment by MatzElectronics** [comment]
Should this be tagged as "staged"?

**Comment by VonSzarvas** [comment]
This is still an issue, right ? 

Also, if you change the TX or RX pin in the init block dropdown, the RXTX,2,1 (or whatever) option doesn't get updated/added to the transmit/receive dropdowns, nor the code behind fdser2_1 variable. The int var declaration does get updated, which breaks things.

I can't explain this in detail here, but if you are working through this you will see anyway. Needs some time.

**Comment by zfi** [comment]
This issue has been resolved. The RX/TX drop down is not made visible until there are multiple serial initialization blocks. I verified that the drop down becomes visible when the second init block is dropped onto the canvas. Tested dragging the serial transmit block and found that the drop down is unaffected.
