### ISSUE TITLE
Toolbar gets bunched up and begins to disappear

### ISSUE THREAD

**Issue by phil-pilgrim** [parallaxinc/solo#416]
Over time, the top toolbar gets bunched up to the left side of the screen:

![solo_toolbar_bunched](https://user-images.githubusercontent.com/61169172/79818571-00547480-833d-11ea-8b18-21033b4273dd.png)

If I save a file, tools on the bar can disappear completely when the bottom "download" bar scrolls up:

![solo_toolbar_blocked](https://user-images.githubusercontent.com/61169172/79818608-0f3b2700-833d-11ea-9a66-61df8678dc10.png)

Dismissing the "download" bar restores the toolbar to its previous bunched-up state. The only way I've found to restore the toolbar to its proper dimension is to reload the Solo URL. The little slider to the right of the condensed toolbar does nothing.

Using Chrome on Win7.

**Comment by zfi** [comment]
The screen shots indicate that this is not an issue with this repository, but in your fork of the project. You might want to check your CSS. It looks like there is an element in the top <div> that is cascading when it should not.

**Comment by phil-pilgrim** [comment]
I made no changes in the page rendering, but maybe Matt did before I forked from his Solo bundle. I'll post this on his github page.

**Comment by PropGit** [comment]
@zfi @phil-pilgrim This seems directly related to Issue #401 I experienced on Solo site 4/2/2020.  Note especially how the scroll bar in phil's screenshots is unstyled and extends up into the header, just like in my posts at the top of #401; whereas the proper look and position is what I later show in [this post](https://github.com/parallaxinc/solo/issues/401#issuecomment-608085669) of the same thread.

I haven't experienced it since that time and believed at the time it had to do with a recent Solo site  update and my browser (also Chrome) mixing new and cached content.

**Comment by zfi** [comment]
This can happen if the bootstrap library is not getting loaded. 

```
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
```
