### ISSUE TITLE
BlocklyProp .svg doesn't compile or download on SoloCup

### ISSUE THREAD

**Issue by PropGit** [parallaxinc/solo#442]
The attached program, built on BlocklyProp months ago and saved as .svg today, compiles on BlocklyProp and on Solo, but will not compile or download on SoloCup.  Strangely, it doesn't even display the overlay saying whether or not it compiled.

[StopLightGame(BP).zip](https://github.com/parallaxinc/solo/files/4669846/StopLightGame.BP.zip)

**Comment by zfi** [comment]
This project exposes at least two issues. Both cause the C code generator to produce nonsensical output which fails to compile.
* The color_value_from block accepts input blocks that produce text values instead of the expected numbers.
* The random number generator block is producing a string output instead of the expected random number.

**Comment by zfi** [comment]
I retested this issue against release 1.5.0-b6, released on 6/9/2020 and found that it compiles without error. @PropGit , if you have time, can you test this again against the SoloCup beta and report back with your results?
