### ISSUE TITLE
Saving Empty Projects

### ISSUE THREAD

**Issue by ataylor-parallax** [parallaxinc/solo#51]
I discovered that an empty project can be saved in solo by importing a blocks file and then deleting all of the code. It is then possible to save and download the code without an empty project warning, which leads to an invalid file type if you try to upload the empty file. 
![image](https://user-images.githubusercontent.com/53913268/62723986-ce75ca80-b9c6-11e9-9f6e-b43438c67f94.png)

**Comment by PropGit** [comment]
Thanks @ataylor-parallax

**Comment by MatzElectronics** [comment]
the latest PR into CDN should address this.

**Comment by MatzElectronics** [comment]
See #49

**Comment by zfi** [comment]
Verified. Any attempt to save or download the project after the blocks are removed results in an alert dialog that informs the user that an empty project cannot be saved.

Closing issue.

**Comment by zfi** [comment]
This issue is resurfacing with blockly core 2.x. We are once again able to save projects that have no blocks defined.

**Comment by zfi** [comment]
@MatzElectronics, the downloadCode() function in editor.js is failing to identify empty projects. The code that is checking for a string length from getXml() is failing because getXml() is now returning a 56 character string, "<xml xmlns="https://developers.google.com/blockly/xml"/>" and not the default string we expected, "<xml xmlns="http://www.w3.org/1999/xhtml">".

```
if (projectData && projectData['board'] !== 'propcfile' && getXml().length < 50) {
```
I have tested this replacement code below and it appears to work. It examines the return from getXml() for a block definition tag and uses that to fail the project save if one is not detected.

```
if (projectData && projectData['board'] !== 'propcfile' && getXml().indexOf('<block') === -1) {
```

Before I commit this, I wanted to ask if you see any pitfalls in the new test.

**Comment by MatzElectronics** [comment]
No, that looks okay.  It does mean, however, that we probably need to
review the code that parses files when they are uploaded/opened to see if
the new xml attributes are going to give that any issues.

**Comment by zfi** [comment]
Good point. I'll dig into that in the morning. Thanks for the mini-review.

**Comment by MatzElectronics** [comment]
Actually,  the download code too...

**Comment by pjewald** [comment]
All paths to save a project appear to properly detect an empty project now.
