### ISSUE TITLE
SD file exists block

### ISSUE THREAD

**Issue by AndyLindsay** [parallaxinc/solo#540]
It would be nice to have a feature that returns 1 if a file exists, or 0 if not.  On its own, it could be = SD file [filename] exists.  Or, if it can be gracefully added to an existing block as an additional dropdown menu item, that's fine too.

**Comment by zfi** [comment]
Created a new File Exists SD block to evaluate the existence of a specified file on the SD card. The block returns a non-zero value if the file exists, otherwise it returns zero.

<img width="218" alt="Screen Shot 2021-08-11 at 1 47 17 PM" src="https://user-images.githubusercontent.com/8442260/129101283-d7c372e7-ff15-46dd-98cb-189c91ac4fc0.png">

### Sample Project
[SD_Card_PAB_Test.svg.zip](https://github.com/parallaxinc/solo/files/6971321/SD_Card_PAB_Test.svg.zip)

This block will be released in v1.6.2 and will be available on [SoloCup](https://solocup.parallax.com) later today.

**Comment by zfi** [comment]
This has been released into Solo 1.6.2.232 - B1.
Closing the issue.
