### ISSUE TITLE
TypeError: a is null on loading new project

### ISSUE THREAD

**Issue by zfi** [parallaxinc/solo#56]
A 'TypeError: a is null' is generated when a project load operation is cancelled. 

![2019-08-09_15-45-07](https://user-images.githubusercontent.com/8442260/62812960-15de8280-babd-11e9-9593-286722d8ae49.png)

Steps to reproduce the error:
* Open Solo home page.
* Click on the Open Project link.
* Select an svg file to load and click OK.
* The Open Project dialog validates the project.
* Click on the Cancel button.

**Comment by MatzElectronics** [comment]
Solo 49 may fix this.  Otherwise, instead of returning null we could return
an empty string.

However,  is the desired behavior in that scenario to return to the splash
screen?

**Comment by zfi** [comment]
We should just stop until we understand what the heck is really going on. I'm done with whack-a-mole.

**Comment by MatzElectronics** [comment]
[solo-49 (cdn-179)](https://github.com/parallaxinc/BlocklyProp-cdn/pull/179) fixes this.  Just tried it in my dev.  It may not have gotten caught before because if the window location changed before the function error happened, it would have just gone on with it's day.

I agree, a full-on refactor of the initialization in it's entirety, perhaps with some added callbacks and/or promises, would help in a lot of these cases.

solo is managing the projectData object very differently than production (and even the local/nwjs app), so I'm not surprised we have moles popping up as we exercise project creation and loading.

If you want to do this systematically, start at the call to the `setupWorkspace()` function, and trace it from there.  You might catch something I've missed.

**Comment by MatzElectronics** [comment]
BTW - it does in fact return to the splash screen (as I thought it was supposed to) when nothing errors.

**Comment by zfi** [comment]
@MatzElectronics, I am still seeing a TypeError in the new code. The Blockly.mainWorkspace is null, and that breaks the DOM hydration. This is after parallaxinc/BlocklyProp-cdn#179 has been merged.

I am really concerned that we are both testing on the same platform but seeing different results. 

```
function getXml() {
    if (Blockly.Xml) {
-->>>    var xml = Blockly.Xml.workspaceToDom(Blockly.mainWorkspace);
        return Blockly.Xml.domToText(xml);
    } else if (projectData && projectData.code) {
        return projectData.code;
    } else {
        // Return the XML for a blank project if none is found.
        return EmptyProjectCodeHeader + '</xml>';
    }
}
```
Here is a screen shot of the failure:

![2019-08-11_09-49-38](https://user-images.githubusercontent.com/8442260/62836908-7a185800-bc1d-11e9-8cc3-97a280dfea84.png)

**Comment by zfi** [comment]
@MatzElectronics, It looks like the problem is in the code below. When loading a new project, it appears that the project details are correctly stored in the browser's localStorge and in the application projectData global. However, the project details are not being submitted to the Blocky core at this point. The redirect is triggering the 'onBeforeLoad', which then runs down the stack to the point where it fails. 

```
function uploadMergeCode(append) {
    // when opening a file when directed from the splash screen in the offline app, load the selected project
    if (!append && isOffline && getURLParameter('openFile') === 'true') {
        window.localStorage.setItem('localProject', JSON.stringify(projectData));
->>        window.location = 'blocklyc.html';
    }
  [...]
```

Let's identify what the onBeforeLoad even handler is really trying to do and address that.

**Comment by zfi** [comment]
Adding a test for a valid Blockly.mainWorkspace gets us past the immediate error and allows the project to load onto the canvas. However, this creates a couple of new issues that may be related to the possibility that the mainWorkspace never gets initialized. 

```
function getXml() {
    if (Blockly.Xml && Blockly.mainWorkspace) {
        var xml = Blockly.Xml.workspaceToDom(Blockly.mainWorkspace);
        return Blockly.Xml.domToText(xml);
    } else if (projectData && projectData.code) {
```
Performing a browser reload while on the editor page causes the project to clear and a Save-As modal to appear. There is also a new TypeError emanating from the Blockly core 
```
TypeError: b is null blockly_compressed.js:1226:182
```

**Comment by MatzElectronics** [comment]
onBeforeLoad or onBeforeUnload?  That's an important distinction...

I'll do some more agressive file upload / open project testing.  I'm
guessing I just did it differently and therefore didn't generate the error
you did.  Can you give me a new outline of steps to follow to replicate the
error (before the addition of a Blockly.mainworkspace test was added to
getXml())?

We shouldn't be calling getXml() without the workspace loaded, so let's
figure out why that's happening.  If it's onBeforeUnload (this happens in
the checkLeave() function), then we need to do the workspace test there
instead.  OnBeforeUnload is there specifically to test if you've made any
changes to your project that have not been saved, and gives you the
opportunity to do that before you navigate away from the page.  If the
workspace hasn't even loaded, then that check should simply pass, and let
you leave the page because you've not actually done any editing of your
blockly code.

Does that make sense?

**Comment by zfi** [comment]
The stack trace clearly shows onBeforeUnload(). Which one is supposed to be called at this point?

The steps I followed are documented at the top of this issue. The last step has changed, in that I am clicking the OK instead of cancel. It actually doesn't matter since clicking either button is causing it to fail.

The test for Blockly.mainWorkspace is just something I tossed in there on my local repo to see if that would really clear this up. The current code in the Develop branch of the CDN is what I am testing against.

As for resolution, I would like to see a very clear path from the point where the project file is actually imported (uploaded) to the setup of the Blockly core for that project. I suspect that the redirect is creating an issue where the Blockly core hydration never gets done during the load and is assuming that something else is responsible for getting that done. This is really difficult to map out without knowing what the intent was behind the current code.

The event handlers would have a better chance of doing the right thing if they didn't have to worry about so many things under the hood. There should be a function that compares the project code in the DOM with the last version that was either loaded or saved to storage (or the database for online). Another function that saves the project at an abstract level and one more pair of functions that implement the abstraction for either online or offline storage.

**Comment by MatzElectronics** [comment]
onBeforeUnload() is triggered by the browser whenever the user tries to
navigate away from the page.

checkLeave() leads to a call to getXml() - we should just check for the
existence of Blockly.mainworkspace in the checkLeave function first
(because if the workspace hasn't loaded yet, there's no need to ask the
user if they'd like to save their project.)

**Comment by zfi** [comment]
The stack trace clearly shows onBeforeUnload(). Which one is supposed to be called at this point?

The steps I followed are documented at the top of this issue. The last step has changed, in that I am clicking the OK instead of cancel. It actually doesn't matter since clicking either button is causing it to fail.

The test for Blockly.mainWorkspace is just something I tossed in there on my local repo to see if that would really clear this up. The current code in the Develop branch of the CDN is what I am testing against.

As for resolution, I would like to see a very clear path from the point where the project file is actually imported (uploaded) to the setup of the Blockly core for that project. I suspect that the redirect is creating an issue where the Blockly core hydration never gets done during the load and is assuming that something else is responsible for getting that done. This is really difficult to map out without knowing what the intent was behind the current code.

The event handlers would have a better chance of doing the right thing if they didn't have to worry about so many things under the hood. There should be a function that compares the project code in the DOM with the last version that was either loaded or saved to storage (or the database for online). Another function that saves the project at an abstract level and one more pair of functions that implement the abstraction for either online or offline storage.

**Comment by zfi** [comment]
Refactored the onunload event handler to determine if we are still handling the openFile process. If we are, then we know that the user wants to move away from the page even though the project load process has not yet completed. In all other use cases, the project has been loaded into the Blockly core and the call to getXml() will return a project.

**Comment by zfi** [comment]
Verified that the TypeError is no longer triggered on project load.
Closing the issue.
